# First Color: #6E43C4
# Second Color: #6A3EC0
# Third Color: #693CBC
# Fourth Color: #663AB7
# Fifth Color: #6238B1
# Sixth Color: #6037AC
# Seventh Color: #5D36A6
# Eigth Color: #5A359E

# Text Color: Dark - #272D37 | Light - #F2EBFF

format = """
[](#6E43C4)\
$env_var\
[](fg:#6E43C4 bg:#6A3EC0)\
$username\
[](fg:#6A3EC0 bg:#693CBC)\
$directory\
[](fg:#693CBC bg:#663AB7)\
$c\
$golang\
$python\
$haskell\
$java\
$julia\
$nodejs\
$rust\
$conda\
[](fg:#663AB7 bg:#6238B1)\
$docker_context\
[](fg:#6238B1 bg:#6037AC)\
$git_branch\
[](fg:#6037AC bg:#5D36A6)\
$time\
[](fg:#5D36A6 bg:#5A359E)\
$cmd_duration\
[ ](fg:#5A359E)\
"""



# Disable the blank line at the start of the prompt
add_newline = true


[env_var.STARSHIP_DISTRO]
style = 'bg:#6E43C4 fg:#F2EBFF'
variable = "STARSHIP_DISTRO"
default = " "
format = '[$env_value]($style)'

[username]
show_always = true
style_user = "bg:#6A3EC0 fg:#F2EBFF"
style_root = "bg:#6A3EC0 fg:#F2EBFF"
format = '[ $user ]($style)'

[directory]
style = "bg:#693CBC fg:#F2EBFF"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "  "
"Downloads" = "  "
"Music" = "  "
"Pictures" = "  "

[c]
symbol = " "
style = "bg:#663AB7 fg:#F2EBFF"
format = '[ $symbol  ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#6238B1 fg:#F2EBFF"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = " "
style = "bg:#6037AC fg:#F2EBFF"
format = '[ $symbol $branch ]($style)'

[golang]
symbol = " "
style = "bg:#663AB7 fg:#F2EBFF"
format = '[ $symbol  ($version) ]($style)'

[python]
symbol = " "
style = "bg:#663AB7 fg:#F2EBFF"
python_binary = ["./venv/bin/python", "./env/Scripts/python", "python", "python3", "python2"]
format = '[ $symbol  ($version)]($style)[ (\($virtualenv\)) ](bg:#663AB7 fg:#F2EBFF)'

[conda]
symbol = " "
style = "bg:#663AB7 fg:#F2EBFF"
ignore_base = false
format = '[ $symbol ($environment) ]($style)'

[haskell]
symbol = " "
style = "bg:#663AB7 fg:#F2EBFF"
format = '[ $symbol  ($version) ]($style)'

[java]
symbol = " "
style = "bg:#663AB7 fg:#F2EBFF"
format = '[ $symbol  ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#663AB7 fg:#F2EBFF"
format = '[ $symbol  ($version) ]($style)'

[nodejs]
symbol = " "
style = "bg:#663AB7 fg:#F2EBFF"
format = '[ $symbol  ($version) ]($style)'

[rust]
symbol = " "
style = "bg:#663AB7 fg:#F2EBFF"
format = '[ $symbol  ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#5D36A6 fg:#F2EBFF"
format = '[ $time ]($style)'

[cmd_duration]
style = "bg:#5A359E fg:#F2EBFF"
format = '[ $duration ]($style)'
