# First Color: #873739
# Second Color: #8B383B
# Third Color: #8D393C
# Fourth Color: #8F393D
# Fifth Color: #91393E
# Sixth Color: #92393E
# Seventh Color: #93393F
# Eigth Color: #98393F

# Text Color: Dark - #272D37 | Light - #F3D3D3

format = """
[](#873739)\
$env_var\
[](fg:#873739 bg:#8B383B)\
$username\
[](fg:#8B383B bg:#8D393C)\
$directory\
[](fg:#8D393C bg:#8F393D)\
$c\
$golang\
$python\
$haskell\
$java\
$julia\
$nodejs\
$rust\
$conda\
[](fg:#8F393D bg:#91393E)\
$docker_context\
[](fg:#91393E bg:#92393E)\
$git_branch\
[](fg:#92393E bg:#93393F)\
$time\
[](fg:#93393F bg:#98393F)\
$cmd_duration\
[ ](fg:#98393F)\
"""



# Disable the blank line at the start of the prompt
add_newline = true


[env_var.STARSHIP_DISTRO]
style = 'bg:#873739 fg:#F3D3D3'
variable = "STARSHIP_DISTRO"
default = " "
format = '[ ]($style)'

[username]
show_always = true
style_user = "bg:#8B383B fg:#F3D3D3"
style_root = "bg:#8B383B fg:#F3D3D3"
format = '[ $user ]($style)'

[directory]
style = "bg:#8D393C fg:#F3D3D3"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "  "
"Downloads" = "  "
"Music" = "  "
"Pictures" = "  "

[c]
symbol = " "
style = "bg:#8F393D fg:#F3D3D3"
format = '[ $symbol  ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#91393E fg:#F3D3D3"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = " "
style = "bg:#92393E fg:#F3D3D3"
format = '[ $symbol $branch ]($style)'

[golang]
symbol = " "
style = "bg:#8F393D fg:#F3D3D3"
format = '[ $symbol  ($version) ]($style)'

[python]
symbol = " "
style = "bg:#8F393D fg:#F3D3D3"
python_binary = ["./venv/bin/python", "./env/Scripts/python", "python", "python3", "python2"]
format = '[ $symbol  ($version)]($style)[(\($virtualenv\)) ](bg:#8F393D fg:#F3D3D3)'

[conda]
symbol = " "
style = "bg:#8F393D fg:#F3D3D3"
ignore_base = false
format = '[ $symbol ($environment) ]($style)'

[haskell]
symbol = " "
style = "bg:#8F393D fg:#F3D3D3"
format = '[ $symbol  ($version) ]($style)'

[java]
symbol = " "
style = "bg:#8F393D fg:#F3D3D3"
format = '[ $symbol  ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#8F393D fg:#F3D3D3"
format = '[ $symbol  ($version) ]($style)'

[nodejs]
symbol = " "
style = "bg:#8F393D fg:#F3D3D3"
format = '[ $symbol  ($version) ]($style)'

[rust]
symbol = " "
style = "bg:#8F393D fg:#F3D3D3"
format = '[ $symbol  ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#93393F fg:#F3D3D3"
format = '[ $time ]($style)'

[cmd_duration]
style = "bg:#98393F fg:#F3D3D3"
format = '[ $duration ]($style)'
