# First Color: #38959E
# Second Color: #37929D
# Third Color: #358F9B
# Fourth Color: #358CA0
# Fifth Color: #3689A2
# Sixth Color: #3785A4
# Seventh Color: #3982A9
# Eigth Color: #3A7EAE

# Text Color: Dark - #272D37 | Light - #CBF4F8

format = """
[](#38959E)\
$env_var\
[](fg:#38959E bg:#37929D)\
$username\
[](fg:#37929D bg:#358F9B)\
$directory\
[](fg:#358F9B bg:#358CA0)\
$c\
$golang\
$python\
$haskell\
$java\
$julia\
$nodejs\
$rust\
$conda\
[](fg:#358CA0 bg:#3689A2)\
$docker_context\
[](fg:#3689A2 bg:#3785A4)\
$git_branch\
[](fg:#3785A4 bg:#3982A9)\
$time\
[](fg:#3982A9 bg:#3A7EAE)\
$cmd_duration\
[ ](fg:#3A7EAE)\
"""



# Disable the blank line at the start of the prompt
add_newline = true


[env_var.STARSHIP_DISTRO]
style = 'bg:#38959E fg:#CBF4F8'
variable = "STARSHIP_DISTRO"
default = " "
format = '[$env_value]($style)'

[username]
show_always = true
style_user = "bg:#37929D fg:#CBF4F8"
style_root = "bg:#37929D fg:#CBF4F8"
format = '[ $user ]($style)'

[directory]
style = "bg:#358F9B fg:#CBF4F8"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "  "
"Downloads" = "  "
"Music" = "  "
"Pictures" = "  "

[c]
symbol = " "
style = "bg:#358CA0 fg:#CBF4F8"
format = '[ $symbol  ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#3689A2 fg:#CBF4F8"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = " "
style = "bg:#3785A4 fg:#CBF4F8"
format = '[ $symbol $branch ]($style)'

[golang]
symbol = " "
style = "bg:#358CA0 fg:#CBF4F8"
format = '[ $symbol  ($version) ]($style)'

[python]
symbol = " "
style = "bg:#358CA0 fg:#CBF4F8"
python_binary = ["./venv/bin/python", "./env/Scripts/python", "python", "python3", "python2"]
format = '[ $symbol  ($version)]($style)[ (\($virtualenv\)) ](bg:#358CA0 fg:#CBF4F8)'

[conda]
symbol = " "
style = "bg:#358CA0 fg:#CBF4F8"
ignore_base = false
format = '[ $symbol ($environment) ]($style)'

[haskell]
symbol = " "
style = "bg:#358CA0 fg:#CBF4F8"
format = '[ $symbol  ($version) ]($style)'

[java]
symbol = " "
style = "bg:#358CA0 fg:#CBF4F8"
format = '[ $symbol  ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#358CA0 fg:#CBF4F8"
format = '[ $symbol  ($version) ]($style)'

[nodejs]
symbol = " "
style = "bg:#358CA0 fg:#CBF4F8"
format = '[ $symbol  ($version) ]($style)'

[rust]
symbol = " "
style = "bg:#358CA0 fg:#CBF4F8"
format = '[ $symbol  ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#3982A9 fg:#CBF4F8"
format = '[ $time ]($style)'

[cmd_duration]
style = "bg:#3A7EAE fg:#CBF4F8"
format = '[ $duration ]($style)'
